In [ ]:
#pip install rpy2

In [1]:
%load_ext rpy2.ipython

In [2]:
%R version

<rpy2.robjects.vectors.ListVector object at 0x1457a0900> [RTYPES.VECSXP]
R classes: ('simple.list',)
[StrSexpVe..., StrSexpVe..., StrSexpVe..., StrSexpVe..., ..., StrSexpVe..., StrSexpVe..., StrSexpVe..., StrSexpVe...]
  platform: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x145832bc0> [RTYPES.STRSXP]
R classes: ('character',)
['x86_64-apple-darwin17.0']
  arch: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x145832d40> [RTYPES.STRSXP]
R classes: ('character',)
['x86_64']
  os: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x145832d80> [RTYPES.STRSXP]
R classes: ('character',)
['darwin17.0']
  system: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x145837300> [RTYPES.STRSXP]
R classes: ('character',)
['x86_64, darwin17.0']
...
  major: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x145837900> [RTYPES.STRSXP]
R classes: ('character',)
['80725']
  minor: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x145837a80> [RTYPES.STRSXP]
R classes: ('character',)
['R']
  year: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x145837d80> [RTYPES.STRSXP]
R classes: ('character',)
['R version 4.1.1 (2021-08-10)']
  month: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x145837d40> [RTYPES.STRSXP]
R classes: ('character',)
['Kick Things']

In [8]:
%R roster <- read.csv('../Data/roster.csv')

    Jersey                Name Position  Inches  Pounds      Class
1        0      Rooks, Patrick        G      74     190   freshman
2        1      Ajukwa, Austin        G      78     205  sophomore
3        3        Holmes, Avry        G      74     205     junior
4        5  Blossomgame, Jaron        F      79     215  sophomore
5       10         DeVoe, Gabe        G      75     200   freshman
6       12           Hall, Rod        G      73     205     senior
7       15     Grantham, Donte        F      80     205   freshman
8       20       Roper, Jordan        G      72     165     junior
9       21  Harrison, Damarcus        G      76     205     senior
10      33         Smith, Josh        F      80     245     junior
11      35       Nnoko, Landry        C      82     255     junior
12      44     McGillan, Riley        G      72     175     junior
13      50        Djitte, Sidy        C      82     240  sophomore

In [9]:
import pandas as pd

In [10]:
pyroster = pd.read_csv('../Data/roster.csv')

In [11]:
pyroster

    Jersey                Name Position  Inches  Pounds      Class
0        0      Rooks, Patrick        G      74     190   freshman
1        1      Ajukwa, Austin        G      78     205  sophomore
2        3        Holmes, Avry        G      74     205     junior
3        5  Blossomgame, Jaron        F      79     215  sophomore
4       10         DeVoe, Gabe        G      75     200   freshman
5       12           Hall, Rod        G      73     205     senior
6       15     Grantham, Donte        F      80     205   freshman
7       20       Roper, Jordan        G      72     165     junior
8       21  Harrison, Damarcus        G      76     205     senior
9       33         Smith, Josh        F      80     245     junior
10      35       Nnoko, Landry        C      82     255     junior
11      44     McGillan, Riley        G      72     175     junior
12      50        Djitte, Sidy        C      82     240  sophomore